# Generated by Django 4.1.7 on 2023-03-17 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento_School',
            fields=[
                ('eventos_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(blank=True, max_length=250, unique=True)),
                ('event_detalhes', models.CharField(blank=True, max_length=250, unique=True)),
                ('event_price', models.CharField(blank=True, max_length=250, unique=True)),
                ('event_data_inicio', models.CharField(blank=True, max_length=250, unique=True)),
                ('event_data_fim', models.CharField(blank=True, max_length=250, unique=True)),
                ('event_hora', models.CharField(blank=True, max_length=250, unique=True)),
                ('event_para_todos1', models.CharField(blank=True, max_length=250, unique=True)),
                ('event_para_todos2', models.CharField(blank=True, max_length=250, unique=True)),
                ('event_para_todos3', models.CharField(blank=True, max_length=250, unique=True)),
                ('event_theme1', models.CharField(blank=True, max_length=250, unique=True)),
                ('event_theme2', models.CharField(blank=True, max_length=250, unique=True)),
                ('event_theme3', models.CharField(blank=True, max_length=250, unique=True)),
                ('event_theme4', models.CharField(blank=True, max_length=250, unique=True)),
                ('event_formadores', models.CharField(blank=True, max_length=250, unique=True)),
                ('event_periodos', models.CharField(blank=True, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formadorcurso',
            fields=[
                ('formador_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periodocourso',
            fields=[
                ('periodo_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cursosguardar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomecursos', models.CharField(blank=True, max_length=250, unique=True)),
                ('comentarioscursos', models.CharField(blank=True, max_length=250, unique=True)),
                ('descriptioncursos', models.CharField(blank=True, max_length=250, unique=True)),
                ('datainiciocursos', models.CharField(blank=True, max_length=250, unique=True)),
                ('datafimcursos', models.CharField(blank=True, max_length=250, unique=True)),
                ('duracaocursos', models.CharField(blank=True, max_length=250, unique=True)),
                ('price', models.CharField(blank=True, max_length=250, unique=True)),
                ('licoes_1', models.CharField(blank=True, max_length=250, unique=True)),
                ('licoes_2', models.CharField(blank=True, max_length=250, unique=True)),
                ('licoes_3', models.CharField(blank=True, max_length=250, unique=True)),
                ('licoes_4', models.CharField(blank=True, max_length=250, unique=True)),
                ('licoes_5', models.CharField(blank=True, max_length=250, unique=True)),
                ('image_curso', models.ImageField(blank=True, upload_to='cursosProfissionais/')),
                ('date_created', models.DateField()),
                ('periodos', models.ManyToManyField(to='cursoAll.periodocourso')),
            ],
        ),
        migrations.CreateModel(
            name='CarteiraMotorista',
            fields=[
                ('carta_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('carta_nome', models.CharField(blank=True, max_length=250, unique=True)),
                ('carta_comentarioscursos', models.CharField(blank=True, max_length=250, unique=True)),
                ('carta_categoria', models.CharField(blank=True, max_length=250, unique=True)),
                ('carta_duracaocursos', models.CharField(blank=True, max_length=250, unique=True)),
                ('carta_price', models.CharField(blank=True, max_length=250, unique=True)),
                ('image_curso', models.ImageField(blank=True, upload_to='cartaPitolto/')),
                ('date_created', models.DateField()),
                ('periodos', models.ManyToManyField(to='cursoAll.periodocourso')),
            ],
        ),
        migrations.CreateModel(
            name='Alunosinscrito',
            fields=[
                ('aluno_id', models.AutoField(primary_key=True, serialize=False)),
                ('aluno_nome', models.CharField(blank=True, max_length=250, unique=True)),
                ('aluno_email', models.CharField(blank=True, max_length=250, unique=True)),
                ('aluno_contactos', models.CharField(blank=True, max_length=250, unique=True)),
                ('aluno_cursosfree', models.CharField(blank=True, max_length=250, unique=True)),
                ('aluno_bilhetebis', models.CharField(blank=True, max_length=250, unique=True)),
                ('alunoprecocursos', models.CharField(blank=True, max_length=250, unique=True)),
                ('aluno_duracaocursos', models.CharField(blank=True, max_length=250, unique=True)),
                ('periodo_id', models.CharField(blank=True, max_length=250, unique=True)),
                ('aluno_cursos', models.ManyToManyField(to='cursoAll.cursosguardar')),
            ],
        ),
    ]
